"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { IndianRupee, Calendar, Building2, User, CheckCircle2, CreditCard, Printer } from "lucide-react";

const MONTHS = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export default function PaymentsPage() {
  const { data: session } = useSession();
  const [payments, setPayments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("tenant");

  const isSeller = session?.user?.role === "seller" || session?.user?.role === "broker";

  useEffect(() => {
    async function load() {
      if (!session) return;
      setLoading(true);
      const res = await fetch(`/api/payments/history?role=${activeTab}`);
      const data = await res.json();
      setPayments(data.payments || []);
      setLoading(false);
    }
    load();
  }, [activeTab, session]);

  const printReceipt = (payment) => {
    const printWindow = window.open('', '', 'height=600,width=800');
    const amountInRupees = ((payment.amount || 0) / 100).toLocaleString("en-IN");
    const monthStr = `${MONTHS[payment.rentMonth]} ${payment.rentYear}`;

    printWindow.document.write(`
      <html>
        <head>
          <title>Rent Receipt - ${monthStr}</title>
          <style>
            body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
            .header { text-align: center; border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 30px; }
            .header h1 { margin: 0; color: #0f172a; font-size: 28px; }
            .header p { color: #64748b; margin: 5px 0 0 0; }
            .details { display: table; width: 100%; border-spacing: 0 15px; margin-bottom: 40px; }
            .row { display: table-row; }
            .label { display: table-cell; font-weight: 600; color: #475569; width: 150px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
            .value { display: table-cell; font-size: 16px; color: #0f172a; font-weight: 500; }
            .amount-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 25px; text-align: center; margin-bottom: 40px; }
            .amount-label { font-size: 14px; text-transform: uppercase; color: #64748b; font-weight: 600; letter-spacing: 1px; }
            .amount-value { font-size: 36px; font-weight: bold; color: #10b981; margin: 10px 0 0 0; }
            .footer { text-align: center; color: #94a3b8; font-size: 13px; border-top: 1px solid #e2e8f0; padding-top: 20px; }
            @media print { body { padding: 0; } .no-print { display: none; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>NestIQ</h1>
            <p>Official Rent Receipt</p>
          </div>
          
          <div class="amount-box">
            <div class="amount-label">Amount Paid</div>
            <div class="amount-value">₹${amountInRupees}</div>
            <p style="margin:5px 0 0 0; color:#10b981; font-weight:600; font-size:14px;">✅ Payment Successful</p>
          </div>

          <div class="details">
            <div class="row">
              <div class="label">Date Paid</div>
              <div class="value">${new Date(payment.createdAt).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</div>
            </div>
            <div class="row">
              <div class="label">Payment ID</div>
              <div class="value">${payment.razorpayPaymentId || 'N/A'}</div>
            </div>
            <div class="row">
              <div class="label">Rent Period</div>
              <div class="value">${monthStr}</div>
            </div>
            <div class="row">
              <div class="label">Property</div>
              <div class="value">${payment.property?.title || 'Property'} — ${payment.property?.address?.locality}, ${payment.property?.address?.city}</div>
            </div>
            <div class="row">
              <div class="label">Tenant</div>
              <div class="value">${payment.tenant?.name} (${payment.tenant?.email})</div>
            </div>
            <div class="row">
              <div class="label">Landlord</div>
              <div class="value">${payment.landlord?.name} (${payment.landlord?.email})</div>
            </div>
            ${payment.notes ? `
            <div class="row">
              <div class="label">Notes</div>
              <div class="value">${payment.notes}</div>
            </div>
            ` : ''}
          </div>

          <div class="footer">
            Generated by NestIQ &bull; This is a computer-generated document and does not require a signature.
          </div>
          
          <script>
            window.onload = function() { window.print(); window.onafterprint = window.close; }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="max-w-4xl mx-auto w-full pb-12">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white tracking-tight">Rent Payments</h1>
        <p className="text-slate-400 mt-2">Track all rent payments made or received through NestIQ.</p>
      </div>

      <div className="flex flex-col gap-8">
        {/* Tabs */}
        {isSeller && (
          <div className="w-full shrink-0 border-b border-white/10 pb-4">
            <nav className="flex flex-row gap-2 overflow-x-auto custom-scrollbar">
              {[
                { key: "tenant", label: "Payments I Made", icon: CreditCard },
                { key: "landlord", label: "Payments Received", icon: IndianRupee },
              ].map((tab) => {
                const Icon = tab.icon;
                const isActive = activeTab === tab.key;
                return (
                  <button
                    key={tab.key}
                    onClick={() => setActiveTab(tab.key)}
                    className={`flex items-center gap-3 px-5 py-2.5 rounded-xl transition-all text-sm font-semibold whitespace-nowrap ${isActive
                      ? "bg-indigo-500/20 text-indigo-400 border border-indigo-500/30 shadow-[0_0_15px_rgba(79,70,229,0.15)]"
                      : "text-slate-400 hover:text-slate-200 hover:bg-white/5 border border-transparent"
                      }`}
                  >
                    <Icon className="w-4 h-4" />
                    {tab.label}
                  </button>
                );
              })}
            </nav>
          </div>
        )}

        <div className="flex-1 bg-white/5 border border-white/10 rounded-3xl p-6 sm:p-8 backdrop-blur-xl shadow-[0_8px_30px_rgba(0,0,0,0.4)]">
          {loading ? (
            <div className="space-y-4">
              {[1, 2, 3].map((i) => (
                <div key={i} className="h-20 bg-white/5 border border-white/10 rounded-2xl animate-pulse" />
              ))}
            </div>
          ) : payments.length === 0 ? (
            <div className="text-center py-16 flex flex-col items-center justify-center text-slate-400">
              <IndianRupee className="w-12 h-12 text-slate-500 mb-4 opacity-50" />
              <p className="font-medium text-lg text-slate-300">No payments found</p>
              <p className="text-sm mt-1">
                {activeTab === "tenant"
                  ? "You haven't made any rent payments yet."
                  : "You haven't received any rent payments yet."}
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {payments.map((p) => (
                <div key={p._id} className="bg-black/20 hover:bg-black/40 transition-colors border border-white/10 rounded-2xl p-5 flex items-center justify-between gap-4">
                  <div className="flex items-center gap-4 min-w-0">
                    <div className="w-12 h-12 bg-emerald-500/10 border border-emerald-500/20 rounded-xl flex items-center justify-center shrink-0 shadow-[0_0_15px_rgba(16,185,129,0.1)]">
                      <CheckCircle2 className="w-6 h-6 text-emerald-400" />
                    </div>
                    <div className="min-w-0">
                      <p className="font-semibold text-white tracking-wide truncate">
                        {p.property?.propertyType} — {p.property?.address?.locality}, {p.property?.address?.city}
                      </p>
                      <div className="flex flex-wrap items-center gap-x-4 gap-y-2 mt-1.5 text-xs text-slate-400">
                        <span className="flex items-center gap-1.5 bg-white/5 px-2 py-1 rounded-md">
                          <Calendar className="w-3.5 h-3.5 opacity-70" />
                          {MONTHS[p.rentMonth]} {p.rentYear}
                        </span>
                        {activeTab === "landlord" ? (
                          <span className="flex items-center gap-1.5 bg-white/5 px-2 py-1 rounded-md">
                            <User className="w-3.5 h-3.5 opacity-70" />
                            {p.tenant?.name}
                          </span>
                        ) : (
                          <span className="flex items-center gap-1.5 bg-white/5 px-2 py-1 rounded-md">
                            <Building2 className="w-3.5 h-3.5 opacity-70" />
                            {p.landlord?.name}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col items-end shrink-0 gap-3">
                    <div className="text-right">
                      <p className="text-lg font-bold text-white tracking-tight">₹{((p.amount || 0) / 100).toLocaleString("en-IN")}</p>
                      <p className="text-xs uppercase tracking-wider text-emerald-400 font-bold mt-1">Paid securely</p>
                    </div>
                    <button
                      onClick={() => printReceipt(p)}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-white/5 hover:bg-white/10 text-slate-300 hover:text-white border border-white/10 hover:border-white/20 rounded-lg text-xs font-semibold transition-all shadow-sm"
                    >
                      <Printer className="w-3.5 h-3.5" />
                      Receipt
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}